name: Build and Publish server ackage

on:
  release:
    types: [created]
jobs:
  ubuntu-latest-cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build examples/server --config Release
          ls -l bin

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
            name: server-${{ github.ref_name }}
            path: bin/server
